// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2Q__tXqG8bV0SDVTjrCyuZ0hGnrz3ruk',
    appId: '1:1071082520202:web:a2e9612b8045e68c57f773',
    messagingSenderId: '1071082520202',
    projectId: 'newway-66b27',
    authDomain: 'newway-66b27.firebaseapp.com',
    storageBucket: 'newway-66b27.appspot.com',
    measurementId: 'G-1MLW8ZH3S0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCms-Wj9Any6r0ud9W0ZZtwNxL4SHjXzgA',
    appId: '1:1071082520202:android:5a0e22498d8b9eee57f773',
    messagingSenderId: '1071082520202',
    projectId: 'newway-66b27',
    storageBucket: 'newway-66b27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK7OBzIAMJzU9JyEEyKFDGennJjCLYy4U',
    appId: '1:1071082520202:ios:cedb2d642adae69857f773',
    messagingSenderId: '1071082520202',
    projectId: 'newway-66b27',
    storageBucket: 'newway-66b27.appspot.com',
    iosBundleId: 'com.rds.geoCamera',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK7OBzIAMJzU9JyEEyKFDGennJjCLYy4U',
    appId: '1:1071082520202:ios:cedb2d642adae69857f773',
    messagingSenderId: '1071082520202',
    projectId: 'newway-66b27',
    storageBucket: 'newway-66b27.appspot.com',
    iosBundleId: 'com.rds.geoCamera',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2Q__tXqG8bV0SDVTjrCyuZ0hGnrz3ruk',
    appId: '1:1071082520202:web:84122323c0c283f357f773',
    messagingSenderId: '1071082520202',
    projectId: 'newway-66b27',
    authDomain: 'newway-66b27.firebaseapp.com',
    storageBucket: 'newway-66b27.appspot.com',
    measurementId: 'G-6N4YTSBRFL',
  );
}
